### ISSUE TITLE
BUG: Does not detect TPUs

### ISSUE THREAD

**Issue by mchaker** [google-coral/demo-multi-video-stream#2]
### Description

Attempting to run the demo on a system with the ASUS IoT 16x-Coral TPU card

```
$  lspci | grep TPU
c3:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c4:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c5:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c6:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c7:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c8:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
c9:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
ca:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
cb:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
cc:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
cd:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
ce:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
cf:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
d0:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
d1:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
d2:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
```

results in the following error:

```
$ ./MultiVideoStreamsDemo 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20220904 15:56:45.577430 180544 InferencerBase.cpp:111] Not enough TPUs found. This demo requires at least 8 TPUs
```

:(

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

ASUS IoT CRL-G116U-P3D

### Other Devices

None

### Programming Language

C++

### Relevant Log Output

```shell
$ ./MultiVideoStreamsDemo 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20220904 15:56:45.577430 180544 InferencerBase.cpp:111] Not enough TPUs found. This demo requires at least 8 TPUs
```
</details>

**Comment by hjonnala** [comment]
Hi @mchaker can you please share the output of below snippet.

```
root@root ~# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycoral.pybind._pywrap_coral import ListEdgeTpus as list_edge_tpus
>>> list_edge_tpus()
[{'type': 'pci', 'path': '/dev/apex_0'}]

```

**Comment by mchaker** [comment]
```
# python3
Python 3.8.13 (default, Aug 23 2022, 09:35:56) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycoral.pybind._pywrap_coral import ListEdgeTpus as list_edge_tpus
>>> list_edge_tpus()
[{'type': 'pci', 'path': '/dev/apex_15'}, {'type': 'pci', 'path': '/dev/apex_8'}, {'type': 'pci', 'path': '/dev/apex_13'}, {'type': 'pci', 'path': '/dev/apex_6'}, {'type': 'pci', 'path': '/dev/apex_11'}, {'type': 'pci', 'path': '/dev/apex_4'}, {'type': 'pci', 'path': '/dev/apex_2'}, {'type': 'pci', 'path': '/dev/apex_0'}, {'type': 'pci', 'path': '/dev/apex_9'}, {'type': 'pci', 'path': '/dev/apex_14'}, {'type': 'pci', 'path': '/dev/apex_7'}, {'type': 'pci', 'path': '/dev/apex_12'}, {'type': 'pci', 'path': '/dev/apex_5'}, {'type': 'pci', 'path': '/dev/apex_10'}, {'type': 'pci', 'path': '/dev/apex_3'}, {'type': 'pci', 'path': '/dev/apex_1'}]
```

**Comment by hjonnala** [comment]
Thanks! Can you also add the below lines at: https://github.com/google-coral/demo-multi-video-stream/blob/main/src/InferencerBase.cpp#L111 and recompile the demo and share the logs please..

```
    LOG(ERROR) << "num_tpus = " << num_tpus;
    LOG(ERROR) << "next_available_tpu_ = " << next_available_tpu_;
    LOG(ERROR) << "all_tpus_ = " << all_tpus_.size();
```

**Comment by mchaker** [comment]
Odd... now I'm getting `Segmentation fault (core dumped)` :(

**Comment by hjonnala** [comment]
Hmm.. can you please try the below steps:

```
cd demo-multi-video-stream/src
sudo rm InferencerBase.cpp 
wget https://raw.githubusercontent.com/hjonnala/snippets/main/InferencerBase.cpp
cd ..
make DOCKER_TARGETS=demo docker-build
./MultiVideoStreamsDemo 
```

**Comment by mchaker** [comment]
Still getting a segfault/core dumped :(

I should be placing `InferencerBase.cpp` in `src/`, right?

Or should I place it in the root directory of the repository?

**Comment by hjonnala** [comment]
My Bad, sorry, yes please replace `InferencerBase.cpp` in `src/` directory.

**Comment by hjonnala** [comment]
Hi @mchaker can you please try the pycoral basic examples and let me know if you are having any issues with them: 
https://coral.ai/docs/dev-board/get-started/#run-pycoral
https://github.com/google-coral/pycoral/tree/master/examples

**Comment by Namburger** [comment]
@mchaker if the basic examples are working and this one is til failing, could you try to grab a backtrace so we can see where it is failing?

```
gdb ./MultiVideoStreamDemo
(gdb) r
...
segfault
(gdb) bt
<This is the backtrace we need>
```
Thanks!

**Comment by mchaker** [comment]
> Hi @mchaker can you please try the pycoral basic examples and let me know if you are having any issues with them: https://coral.ai/docs/dev-board/get-started/#run-pycoral https://github.com/google-coral/pycoral/tree/master/examples

@hjonnala for the first "get started" exercise, I received an error:

```
python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/classify_image.py", line 121, in <module>
    main()
  File "examples/classify_image.py", line 71, in main
    interpreter = make_interpreter(*args.model.split('@'))
  File "/usr/local/lib/python3.8/site-packages/pycoral/utils/edgetpu.py", line 87, in make_interpreter
    delegates = [load_edgetpu_delegate({'device': device} if device else {})]
  File "/usr/local/lib/python3.8/site-packages/pycoral/utils/edgetpu.py", line 52, in load_edgetpu_delegate
    return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})
  File "/usr/local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1
```

this is after installing `edgetpu-compiler` and `libedgetpu1-max` on ubuntu.

For the second one, I received the same error when trying the first example. I think they will all hit the same issue since `libedgetpu` seems essential. :(

**Comment by Namburger** [comment]
humnn, that definitely sounds like a problem with libedgetpu, which ubuntu version do you have?
Also, can you also show us the output of these commands?
```
dpkg -l | grep libedgetpu
ldd --version
```

**Comment by mchaker** [comment]
Yes, hopefully tonight. Thank you for your help with this

Ubuntu 22.04

**Comment by hjonnala** [comment]
Fell free to reopen if you are still having the issue. Thanks!
